version: '3'
services:
  app1:
    build: ./5.1p
    image: yuyuccc/323class-app1
    volumes:
      - ./5.1p:/usr/src/app
    ports:
      - 4010:4010
    networks:
      - mynetwork
  app2:
    build: ./week4
    image: yuyuccc/323class-app2
    volumes:
      - ./week4:/usr/src/app
    ports:
      - 4020:4020
    networks:
      - mynetwork
networks:
  mynetwork:

